#! /bin/bash

for i in {1..114}
do
	curl -s "https://api.quran.com/api/v4/quran/translations/131?chapter_number=${i}" | jq "." | grep "\"text\":" | sed "s/<sup.*<\/sup>//g ; s/\"//g ; s/:\ /:/" | cut -d ":" -f 2 > "${i}-no-surah.t.txt"

	j=1
	while read line
	do
		echo "$j: $line" >>  ${i}-no-surah.txt
		j=$((j+1))
	done < ${i}-no-surah.t.txt
	
	rm ${i}-no-surah.t.txt
	echo "download ${i}-no-surah and line count is:$(wc -l ${i}-no-surah.txt)"
done
