#! /bin/bash

for i in {1..114}
do
	curl -s "https://api.quran.com/api/v4/quran/translations/131?chapter_number=${i}" |
		jq "." |
		grep "\"text\":" |
		sed "s/:\ /:/" |
		cut -d ":" -f 2 |
		sed 's/^"// ; s/"$//' > "${i}-no-surah.t.txt"

	j=1
	while read line
	do
		if [ ! -z "$( echo "$line" | grep -Eo "<sup foot_note=[0-9]*>[0-9]*</sup>" | head -1 )" ]
		then
			echo "$line" | grep -Eo "<sup foot_note=[0-9]*>[0-9]*</sup>" > ${i}-no-surah-${j}-no-line.f.t.txt
				
			# echo "$line" | sed 's/<sup\ foot_note=[0-9]*>/\[/g; s/<\/sup>/\]/g'

			while read foot
			do
				footnoteF="$(curl -s "https://api.qurancdn.com/api/qdc/foot_notes/$(echo "$foot" | cut -d '=' -f 2 | cut -d '>' -f 1)" |
					jq "." |
					grep "text\":" |
					sed 's/"text":\ "<div><p>\ //; s/<\/p><\/div>",//; s/^\s\+//')"

				footnoteN="$( echo "$foot" | sed 's/<sup\ foot_note=[0-9]*>/\[/g; s/<\/sup>/\]/g')"
				echo -e "\t$footnoteN $footnoteF" >> ${i}-no-surah-${j}-no-line-formatted.footnote.t.txt

			done < ${i}-no-surah-${j}-no-line.f.t.txt
		
			echo -e "$j: $(echo "$line" | sed 's/<sup\ foot_note=[0-9]*>/\[/g; s/<\/sup>/\]/g')\n$(cat ${i}-no-surah-${j}-no-line-formatted.footnote.t.txt )" >> ${i}-no-surah.txt

			rm ${i}-no-surah-${j}-no-line.f.t.txt ${i}-no-surah-${j}-no-line-formatted.footnote.t.txt
		
		else
		echo "$j: $line" >>  ${i}-no-surah.txt

		fi

		j=$((j+1))
	done < ${i}-no-surah.t.txt
	
	rm ${i}-no-surah.t.txt
	
	echo "download ${i}-no-surah"
done

